[build]
  command = "pip install -r requirements.txt"
  
[context.production.environment]
  WEB_CONCURRENCY = "3"
  PORT = "5000"

[build.environment]
  FLASK_ENV = "production"

[[redirects]]
  from = "/*"
  to = "templates/index.html"
  status = 200
